### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by rustiever** [YASHBRO/YASHBRO#3]
you invited me for your organization, may i know what is the reason? 
is there any project we need to collaborate??

**Comment by YASHBRO** [comment]
@rustiever Sorry but I don't remember inviting you anywhere
Can you please help me recall how I invited you

**Comment by rustiever** [comment]
![image](https://user-images.githubusercontent.com/60929919/146127399-4b9ca933-4fd5-4a86-ad18-e6ab5e4bfc04.png)
here is the invitation
